name: build-rails-buildpack

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-rails-buildpack.yml'
      - '**/Dockerfile'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.2.11'
            folder: '3.x' # bookworm for linux/amd64
            tag: '3.2.11-bookworm@sha256:d68250c0e3974511b6b8d489afb9a5e8e45aadd41dd841f6e035f7c4c03f1a54'
          - ruby: '3.3.11'
            folder: '3.x' # bookworm for linux/amd64
            tag: '3.3.11-bookworm@sha256:cdf1bbc7daaef640c62e834fa624c831b00ebb2dbf0b522e3bc43db97aa878c7'
          - ruby: '3.4.9'
            folder: '3.x' # bookworm for linux/amd64
            tag: '3.4.9-bookworm@sha256:e467a23bc24df75574b42ada7e034b38dc0e7cc52a02a911e02a75d824e0e2a6'
          - ruby: '4.0.4'
            folder: '4.x' # bookworm for linux/amd64
            tag: '4.0.4-bookworm@sha256:d0447ec9bef270a7f7a0b0be3410813fd184d56cfe39775e7c7c897fb2023c5d'
    container:
      image: docker:git
      env:
        DOCKER_REPOSITORY: public.ecr.aws/degica/rails-buildpack
        DOCKER_BUILDKIT: '1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
    - name: prepare
      run: |-
        apk add --no-cache python3 py3-pip
        pip3 install --break-system-packages --upgrade pip
        pip3 install --break-system-packages awscli
    - name: workaround git security
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
    - name: setup
      run: git submodule update --init
    - name: build_and_push
      run: |-
        cd rails-buildpack/${{ matrix.folder }}
        if [[ ${GITHUB_REF##*/} == 'master' ]]; then
            IMAGE_TAG=${{ matrix.ruby }}
        else
            IMAGE_TAG=test-${GITHUB_REF##*/}-${{ matrix.ruby }} # branch name for dev usecases
        fi
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/degica
        docker build . -t $DOCKER_REPOSITORY:$IMAGE_TAG --build-arg RUBY_TAG=${{ matrix.tag }} --pull
        docker images
        docker push $DOCKER_REPOSITORY:$IMAGE_TAG
        docker tag $DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REPOSITORY:latest
        docker push $DOCKER_REPOSITORY:latest
