name: build-rails-base

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-rails-base.yml'
      - '**/Dockerfile'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.2.11'
            folder: '3.x' # slim bookworm for linux/amd64
            tag: '3.2.11-slim-bookworm@sha256:1bb3b14e4cbf883f50c92bf48efdeea2126e5a2de4764c13cd7b78fb36e71052'
          - ruby: '3.3.11'
            folder: '3.x' # slim bookworm for linux/amd64
            tag: '3.3.11-slim-bookworm@sha256:95f7e890438560486113d1adcf0791575f90c4e02145c6dab0bc4b6b0a2bd024'
          - ruby: '3.4.9'
            folder: '3.x' # slim bookworm for linux/amd64
            tag: '3.4.9-slim-bookworm@sha256:510c441d2541a5ef8c6a657a67ae98d5b0c6acdd886691690ed30f986095f55e'
          - ruby: '4.0.4'
            folder: '4.x' # slim bookworm for linux/amd64
            tag: '4.0.4-slim-bookworm@sha256:a9d95f9aa853c0d818f9f9b31f536adb24fb83d866e8fd1a4d3fcc5a2f229193'
    container:
      image: docker:git
      env:
        DOCKER_REPOSITORY: public.ecr.aws/degica/rails-base
        DOCKER_BUILDKIT: '1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
    - name: prepare
      run: |-
        apk add --no-cache python3 py3-pip
        pip3 install --break-system-packages --upgrade pip
        pip3 install --break-system-packages awscli
    - name: workaround git security
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
    - name: setup
      run: git submodule update --init
    - name: build_and_push
      run: |-
        cd rails-base/${{ matrix.folder }}
        if [[ ${GITHUB_REF##*/} == 'master' ]]; then
            IMAGE_TAG=${{ matrix.ruby }}
        else
            IMAGE_TAG=test-${GITHUB_REF##*/}-${{ matrix.ruby }} # branch name for dev usecases
        fi
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/degica
        docker build . -t $DOCKER_REPOSITORY:$IMAGE_TAG --build-arg RUBY_TAG=${{ matrix.tag }} --pull
        docker images
        docker push $DOCKER_REPOSITORY:$IMAGE_TAG
        docker tag $DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REPOSITORY:latest
        docker push $DOCKER_REPOSITORY:latest
