name: build-rails-base

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-rails-base.yml'
      - '**/Dockerfile'

permissions:
  contents: read
  id-token: write

env:
  ECR_REGISTRY: public.ecr.aws
  ECR_REPOSITORY: degica/rails-base

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.2.11'
            folder: '3.x' # slim bookworm for linux/amd64
            tag: '3.2.11-slim-bookworm@sha256:1bb3b14e4cbf883f50c92bf48efdeea2126e5a2de4764c13cd7b78fb36e71052'
          - ruby: '3.3.11'
            folder: '3.x' # slim bookworm for linux/amd64
            tag: '3.3.11-slim-bookworm@sha256:95f7e890438560486113d1adcf0791575f90c4e02145c6dab0bc4b6b0a2bd024'
          - ruby: '3.4.11'
            folder: '3.x' # slim bookworm for linux/amd64
            tag: '3.4.11-slim-bookworm@sha256:72e67ff51f595b44ce2bd04e4b8d5203759a0ff51ba3ea8800514c50d91c3b24'
          - ruby: '4.0.7'
            folder: '4.x' # slim bookworm for linux/amd64
            tag: '4.0.7-slim-bookworm@sha256:b21bc6c2360f7b7b615ff8860f239b12b2c6634ec026712745743b0661ac14b9'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Configure AWS credentials for Public ECR
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.PUBLIC_ECR_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Public ECR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Construct image tag
        id: image-tag
        run: |
          if [[ ${GITHUB_REF##*/} == 'master' ]]; then
            echo "tag=${{ matrix.ruby }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=test-${GITHUB_REF##*/}-${{ matrix.ruby }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push container image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          provenance: false
          context: "{{defaultContext}}:rails-base/${{ matrix.folder }}"
          build-args: RUBY_TAG=${{ matrix.tag }}
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.image-tag.outputs.tag }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
