name: clone-images

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/clone-images.yml'

permissions:
  id-token: write

env:
  ECR_REGISTRY: public.ecr.aws

jobs:
  mirror:
    strategy:
      matrix:
        include:
          - image: "selenium/standalone-chrome"
            tag: "4.7.1"
          - image: "selenium/standalone-chrome"
            tag: "4.25.0"
          - image: "selenium/standalone-chrome"
            tag: "4.27.0"
          - image: "selenium/standalone-chrome-debug"
            tag: "3.141.59"
          - image: "degicigel/echo"
            tag: "1.0"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for Public ECR
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.PUBLIC_ECR_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Public ECR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Construct image tag
        id: image-tag
        run: |
          DOCKERHUB_IMAGE="${{ matrix.image }}"
          ORIGINAL_TAG="${{ matrix.tag }}"
          if [[ ${GITHUB_REF##*/} == 'master' ]]; then
            echo "tag=$ORIGINAL_TAG" >> "$GITHUB_OUTPUT"
          else
            echo "tag=test-${GITHUB_REF##*/}-$ORIGINAL_TAG" >> "$GITHUB_OUTPUT"
          fi

      - name: Construct image name
        id: image-name
        run: |
          IMAGE_NAME=`echo "${{ matrix.image }}" | sed 's/\//-/'`
          echo "name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"

      - name: Pull and push container image
        env:
          SOURCE_IMAGE: ${{ matrix.image }}:${{ matrix.tag }}
          DESTINATION_IMAGE: ${{ env.ECR_REGISTRY }}/degica/${{ steps.image-name.outputs.name }}:${{ steps.image-tag.outputs.tag }}
        run: |
          docker pull $SOURCE_IMAGE
          docker tag $SOURCE_IMAGE $DESTINATION_IMAGE
          docker push $DESTINATION_IMAGE
          echo "$DESTINATION_IMAGE pushed"
